import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://fit4steps.com';

  const routes = [
    '',
    '/v1',
    '/v2',
    '/v3',
    '/v4',
    '/v5',
    '/v6',
    '/about',
    '/about/trainers',
    '/senior-fitness',
    '/senior-fitness/fifty-plus',
    '/senior-fitness/strength-seniors',
    '/senior-fitness/knee-therapy',
    '/senior-fitness/mobility-balance',
    '/services',
    '/services/personal-training-at-home',
    '/services/female-fitness-trainers',
    '/services/couple-training',
    '/services/kids-fitness-functional-training',
    '/services/prenatal-postnatal-yoga',
    '/services/corrective-exercise-lifestyle-diseases',
    '/services/stress-management-training',
    '/services/personalized-online-training',
    '/services/corporate-wellness-yoga',
    '/locations',
    '/locations/noida',
    '/locations/delhi',
    '/locations/gurugram',
    '/senior-citizen-fitness-trainer-at-home-delhi',
    '/senior-citizen-fitness-trainer-at-home-gurugram',
    '/personal-fitness-trainer-delhi',
    '/personal-trainer-greater-kailash-delhi',
    '/mobility-exercises-for-senior-citizens',
    '/female-fitness-trainers-in-delhi',
    '/couples-fitness-training-at-home-delhi',
    '/fitness-training-for-kids-noida',
    '/personal-fitness-training-for-50-plus',
    '/programs',
    '/programs/weight-training',
    '/programs/yoga',
    '/programs/power-yoga',
    '/programs/pilates',
    '/programs/aerobics',
    '/programs/kick-boxing',
    '/programs/stretching-mobility',
    '/programs/ball-exercise',
    '/programs/circuit-training',
    '/programs/hiit',
    '/programs/trx-exercise',
    '/programs/sports-games',
    '/blog',
    '/blog/exercises-for-knee-pain',
    '/blog/safe-exercises-for-elderly',
    '/blog/benefits-of-strength-training-after-50',
    '/blog/joint-mobility-routine-for-seniors',
    '/blog/posture-correction-desk-workers',
    '/blog/diastasis-recti-postnatal-recovery',
    '/blog/screen-time-and-kids-posture',
    '/blog/how-to-set-up-home-workout-space',
    '/success-stories',
    '/faq',
    '/contact',
    '/privacy-policy',
    '/terms'
  ];

  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: route === '' || route.startsWith('/blog') ? 'weekly' : 'monthly',
    priority: route === '' ? 1.0 : route.startsWith('/senior-fitness') || route.startsWith('/locations') ? 0.9 : 0.8,
  }));
}
